spring:
  datasource:
    url: jdbc:tc:mysql:8.0.36:///shopdb
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: false
        jdbc:
          time_zone: UTC
    open-in-view: false

logging:
  level:
    root: warn
